### PR TITLE
fix: fixes path issues on windows

### LINKED ISSUE #822: No web interface on Shiori 1.6.0 RC 6
Hi all,

Seems there are some files missing in the executable.
Because the web interface seems not to come up.

Here's the log:

$ shiori server --portable

time="2024-01-26T19:42:47+01:00" level=warning msg="SHIORI_HTTP_SECRET_KEY is not set, using random value. This means th
at all sessions will be invalidated on server restart."
time="2024-01-26T19:42:48+01:00" level=info msg="Starting Shiori v1.6.0-rc.6"
time="2024-01-26T19:42:48+01:00" level=info msg="starting http server" addr=":8080"
time="2024-01-26T19:43:13+01:00" level=error msg="requested frontend file not found" error="open assets\\css\\style.css:
 file does not exist" path=/css/style.css
time="2024-01-26T19:43:13+01:00" level=error msg="requested frontend file not found" error="open assets\\js\\vue.min.js:
 file does not exist" path=/js/vue.min.js
time="2024-01-26T19:43:13+01:00" level=error msg="requested frontend file not found" error="open assets\\js\\url.min.js:
 file does not exist" path=/js/url.min.js
time="2024-01-26T19:43:13+01:00" level=error msg="requested frontend file not found" error="open assets\\js\\page\\base.
js: file does not exist" path=/js/page/base.js
time="2024-01-26T19:43:13+01:00" level=error msg="requested frontend file not found" error="open assets\\js\\page\\home.
js: file does not exist" path=/js/page/home.js
time="2024-01-26T19:43:13+01:00" level=error msg="requested frontend file not found" error="open assets\\js\\page\\setti
ng.js: file does not exist" path=/js/page/setting.js
time="2024-01-26T19:43:13+01:00" level=error msg="requested frontend file not found" error="open assets\\js\\component\\
dialog.js: file does not exist" path=/js/component/dialog.js
time="2024-01-26T19:43:13+01:00" level=error msg="requested frontend file not found" error="open assets\\res\\favicon-16
x16.png: file does not exist" path=/res/favicon-16x16.png
time="2024-01-26T19:43:13+01:00" level=error msg="requested frontend file not found" error="open assets\\res\\apple-touc
h-icon-152x152.png: file does not exist" path=/res/apple-touch-icon-152x152.png

### PR DESCRIPTION
**Pull request by Monirzadeh**
This PR try to fix failed test in windows and fix #822 
TODO:
- [x] thumb path fix
- [x] serve frontend files in windows and pass style css test in` frontpage_test.go` for windows.
- [x] `failed to create destination dir  file does not exist.`
  - everywhere we us `WriteFile` this test failed in windows. core test failed because of that.
   - maybe this is a false negative. i can pass that with some change and manual testing work fine in windows too. i should be sure about that. (pass a not absolute path for temp in unit test and it work fine)
for example change this two line  
https://github.com/go-shiori/shiori/blob/84e5b09c4c9944fc881ad6e1c6a5224b6fa07e42/internal/core/ebook_test.go#L25-L26
to this and test will pass
- [x] `The process cannot access the file because it is being used by another process.`
  - it happen in golang 1.20 for record https://github.com/golang/go/issues/51442 and review later
  - `TestReadDotEnv` everywhere we use `os.RemoveAll`
```
tempDir := "tmpdir"
dstDir := "dstdir"
```
- [x] cleanup the code and unify variable names

Fixes #829
Fixes #824
Fixes #823 
Close #827 
Close #822

### CODE REVIEW

File: internal/config/config_test.go [hunk 1]
```diff
@@ -65,37 +65,26 @@ func TestReadDotEnv(t *testing.T) {
 		{"multiple variable", "SHIORI_HTTP_PORT=9999\nSHIORI_HTTP_SECRET_KEY=123123", map[string]string{"SHIORI_HTTP_PORT": "9999", "SHIORI_HTTP_SECRET_KEY": "123123"}},
 	} {
 		t.Run(testCase.name, func(t *testing.T) {
-			tmpDir, err := os.MkdirTemp("", "")
-			require.NoError(t, err)
-
+			tmpDir := t.TempDir() + "/local"
```
Comment (fmartingr) [inline internal/config/config_test.go:68]: What is the purpose of the `/local` path?

File: internal/config/config_test.go [hunk 2]
```diff
@@ -65,37 +65,26 @@ func TestReadDotEnv(t *testing.T) {
...
-			})
-
 			// Write the .env file in the temporary directory
 			handler, err := os.OpenFile(".env", os.O_CREATE|os.O_WRONLY, 0655)
 			require.NoError(t, err)
 			handler.Write([]byte(testCase.line + "\n"))
 			handler.Close()
 
 			e := readDotEnv(log)
+			os.RemoveAll(".env")
```
Comment (fmartingr) [inline internal/config/config_test.go:78]: I don't think youneed to remove the `.env` file since the test will remove the temp dir automatically

**Comment by fmartingr** [comment]
Try this changes to the database tests:  
[dbtest.patch](https://github.com/go-shiori/shiori/files/14136729/dbtest.patch)

File: internal/config/config_test.go (hunk 2 above)
Comment (fmartingr) [reply internal/config/config_test.go:78]: So windows is ignoring the `os.Chdir` I guess? Mhmm

Comment (fmartingr) [reply internal/config/config_test.go:78]: Oh, `os.Chdir` returns an error and we are not checking it. Maybe we can get more information from that.

**Comment by fmartingr** [comment]
Could be a permissions issue on Windows maybe?

File: internal/config/config_test.go [hunk 3]
```diff
@@ -65,37 +65,26 @@ func TestReadDotEnv(t *testing.T) {
 		{"multiple variable", "SHIORI_HTTP_PORT=9999\nSHIORI_HTTP_SECRET_KEY=123123", map[string]string{"SHIORI_HTTP_PORT": "9999", "SHIORI_HTTP_SECRET_KEY": "123123"}},
 	} {
 		t.Run(testCase.name, func(t *testing.T) {
-			tmpDir, err := os.MkdirTemp("", "")
-			require.NoError(t, err)
-
+			tmpDir := t.TempDir() + "/local"
 			os.Chdir(tmpDir)
```
Comment (fmartingr) [inline internal/config/config_test.go:69]:
```suggestion
			require.NoError(t, os.Chdir(tmpDir))
```

File: internal/config/config_test.go (hunk 2 above)
Comment (fmartingr) [reply internal/config/config_test.go:78]: I still think this shouldn't be required. If this test is not behaving properly in windows we should skip it in that system and go back to it once the upstream issue is resolved.

File: internal/core/ebook_test.go [hunk 4]
```diff
@@ -34,138 +34,148 @@ func TestGenerateEbook(t *testing.T) {
...
-
-			bookmark, err := core.GenerateEbook(deps, mockRequest, fp.Join(tempDir, "1"))
+			bookmark, err := core.GenerateEbook(deps, mockRequest, dstFile)
 
 			assert.True(t, bookmark.HasEbook)
 			assert.NoError(t, err)
 		})
 		t.Run("ebook generate with valid BookmarkID EbookExist ImagePathExist ReturnWithHasEbookTrue", func(t *testing.T) {
-			dstDir := t.TempDir()
+			//dstDir := "/ebook/2"
```
Comment (fmartingr) [inline internal/core/ebook_test.go:46]:
```suggestion
```

File: internal/core/ebook_test.go [hunk 5]
```diff
@@ -34,138 +34,148 @@ func TestGenerateEbook(t *testing.T) {
...
+				DataDir:     temp,
 				ContentType: "text/html",
 			}
 			// Create the thumbnail file
 			imagePath := model.GetThumbnailPath(&bookmark)
-			deps.Domains.Storage.FS().MkdirAll(fp.Dir(imagePath), os.ModePerm)
+			imagedirPath := fp.Dir(imagePath)
+			deps.Domains.Storage.FS().MkdirAll(imagedirPath, os.ModePerm)
 			file, err := deps.Domains.Storage.FS().Create(imagePath)
+			log.Println(file.Name())
```
Comment (fmartingr) [inline internal/core/ebook_test.go:66]:
```suggestion
```

File: internal/core/ebook_test.go [hunk 6]
```diff
@@ -2,6 +2,7 @@ package core_test
 
 import (
 	"context"
+	"log"
```
Comment (fmartingr) [inline internal/core/ebook_test.go:5]:
```suggestion
```

File: internal/core/processing_test.go [hunk 7]
```diff
@@ -24,30 +22,27 @@ func TestDownloadBookImage(t *testing.T) {
 		t.Run("fails", func(t *testing.T) {
 			// images is too small with unsupported format with a valid URL
 			imageURL := "https://github.com/go-shiori/shiori/blob/master/internal/view/assets/res/apple-touch-icon-152x152.png"
-			tempDir := t.TempDir()
-			dstPath := fp.Join(tempDir, "1")
-			defer os.Remove(dstPath)
+			temp := t.TempDir()
+			dstFile := temp + "/image.png"
```
Comment (fmartingr) [inline internal/core/processing_test.go:26]:
```suggestion
			dstFile := filepath.Join(temp, "image.png")
```

File: internal/core/processing_test.go [hunk 8]
```diff
@@ -59,16 +54,14 @@ func TestDownloadBookImage(t *testing.T) {
 
 			// Arrange
 			imageURL := server.URL + "/medium_image.png"
-			tempDir := t.TempDir()
-			dstPath := fp.Join(tempDir, "1")
-			defer os.Remove(dstPath)
+			dstFile := "tempDir/medium_image.png"
```
Comment (fmartingr) [inline internal/core/processing_test.go:57]:
```suggestion
			dstFile := filepath.Join(tempDir, "medium_image.png")
```

File: .github/workflows/_test.yml [hunk 9]
```diff
@@ -60,3 +60,32 @@ jobs:
...
+        path: |
+          ~/.cache/go-build
+          ~/go/pkg
+        key: golangci-lint.cache-{platform-arch}-{interval_number}-{go.mod_hash}
+        restore-keys: |
+          golangci-lint.cache-{interval_number}-
+          golangci-lint.cache-
+        env:
+          CGO_ENABLED=0
+    - run: make unittest GO_TEST_FLAGS="-tags test_sqlite_only"
```
Comment (fmartingr) [inline .github/workflows/_test.yml:89]: We probably need the `CGO_ENABLED=0` here and in the step below this onw.

**Review by fmartingr — CHANGES_REQUESTED** [review]
Thanks for researching into this, I've left a few comments around, mostly around path generation (we should use `filepath.Join` or `path.Join` where appropiate), and to remove some other temporary things.

File: internal/core/processing_test.go [hunk 10]
```diff
@@ -24,32 +26,38 @@ func TestDownloadBookImage(t *testing.T) {
...
 			// Assert
 			assert.NoError(t, err)
-			assert.True(t, deps.Domains.Storage.FileExists(dstPath))
+			assert.True(t, deps.Domains.Storage.FileExists(dstFile))
 		})
 		t.Run("successful download medium size image", func(t *testing.T) {
+			temp, err := os.MkdirTemp("", "")
+			require.NoError(t, err)
 			// create a file server handler for the 'testdata' directory
 			fs := http.FileServer(http.Dir("../../testdata/"))
```
Comment (fmartingr) [inline internal/core/processing_test.go:62]:
```suggestion
			fs := http.FileServer(http.Dir(t.TempDir()))
```

**Comment by fmartingr** [comment]
Oh yeah you are right 🤦

File: .github/workflows/_test.yml (hunk 9 above)
Comment (fmartingr) [reply .github/workflows/_test.yml:90]: you can add:

```yaml
env:
          CGO_ENABLED=0
```

as a global environmnet before the workflow steps:

https://docs.github.com/en/actions/learn-github-actions/variables#defining-environment-variables-for-a-single-workflow

**Comment by fmartingr** [comment]
I have pushed a commit to your branch with the `env` change. 

Can you check the test change for these lines: https://app.codecov.io/gh/go-shiori/shiori/pull/829/indirect-changes#79a7897873ac5d4fcc5ba2f5c3b3e482-R138

It seems we have stopped testing part of the _happy path_. I'm not concerned about the `if err != nil` not being tested, but the `if err == nil` should be covered be tests, more so if tests were covering those lines before.

File: internal/core/ebook_test.go [hunk 11]
```diff
@@ -34,138 +34,146 @@ func TestGenerateEbook(t *testing.T) {
...
 			}
 			defer file.Close()
 
-			bookmark, err = core.GenerateEbook(deps, mockRequest, model.GetEbookPath(&bookmark))
-			expectedImagePath := "/bookmark/2/thumb"
+			bookmark, err = core.GenerateEbook(deps, mockRequest, dstFile)
+			expectedImagePath := string(fp.Separator) + fp.Join("bookmark", "2", "thumb")
 			assert.NoError(t, err)
 			assert.True(t, bookmark.HasEbook)
+			log.Println(bookmark.ImageURL)
```
Comment (fmartingr) [inline internal/core/ebook_test.go:74]:
```suggestion
			t.Log(bookmark.ImageURL)
```

File: internal/core/ebook_test.go (hunk 6 above)
Comment (fmartingr) [reply internal/core/ebook_test.go:5]:
```suggestion
```

File: internal/core/ebook_test.go [hunk 12]
```diff
@@ -34,138 +34,146 @@ func TestGenerateEbook(t *testing.T) {
...
 
-			bookmark, err := core.GenerateEbook(deps, mockRequest, tempDir)
+			bookmark, err := core.GenerateEbook(deps, mockRequest, dstFile)
 
 			assert.Equal(t, model.BookmarkDTO{
 				ID:       0,
 				HasEbook: false,
 			}, bookmark)
-			assert.Error(t, err)
+			log.Println(err)
```
Comment (fmartingr) [inline internal/core/ebook_test.go:126]:
```suggestion
			t.Log(err)
```

**Review by fmartingr — APPROVED** [review]
Ok. just the `log` issue in the test, everything seems ready to go. Again, awesome work, thanks a lot for digging into this in windows :)
