### PR TITLE
fix: Ensure bookmark files are correctly downloaded before deleting current ones

### LINKED ISSUE #524: The application does not remove the thumbnail file from the FS if it is removed in the original article
## Data
- **Shiori version**: commit [77269b7](https://github.com/go-shiori/shiori/commit/77269b7a6420220a0af1fc9c381b5319fbdde686)
- **Database Engine**: SQLite
- **Operating system**: Windows 8.1
- **CLI/Web interface/Web Extension**: CLI

## Describe the bug / actual behavior
The problem is described in the title of the issue.

## Expected behavior
If a thumbnail is removed from the original article, then it should also be removed from the file system.

## To Reproduce
1. Save any HTML page with thumbnail from the internet to the localhost and serve it with any way (e. g. `python -m SimpleHTTPServer 8080`.
2. Add a link to this page in Shiori. As you can see, an image file is created in the `thumb` directory.
3. Remove all text and all image tags from the saved page.
4. Click the update archive button. I also check both checkboxes: "Keep the old title and excerpt" and "Update archive as well".
5. As you can see, the site thumbnail disappeared from Shiori's interface, but it remained in the file system.

### LINKED ISSUE #634: Remove old cache if updating cache done without problem
>We will need to be cautious in the future and do not remove content, archive or bookmark if we find problems when updating the cache. We could save the new one to a temporary location while we work, and if everything succeeds, replace the current one. We can create an issue for this.

_Originally posted by @fmartingr in https://github.com/go-shiori/shiori/pull/623#discussion_r1255429395_

### PR DESCRIPTION
**Pull request by Monirzadeh**
This pull request should recover old version of Archive and e-book if download Processes failed.
It should close #634 
fix #524
# TODO:
- [x] generate ebook to dstPath
- [x] Archive Recover
- [x] E-Book Recover
- [x] Thumb Recover
- [x] E-Book Download API should manage if ebook file exist not download as TODO in code
- [x] if download Failed and recover old file, it should report to user in UI
- [x] thumbnail will update in update archive #524 #680 
- [x] update old unit test.
- [x] add more unit test to cover `processing.go` 87.7% 
- [x] add test image file to repository
- [x] replace URL with sample file

# Things need more time:
should we recover thumb image? What if thumb image remove from source like #524. How we should detect that

### CODE REVIEW

**Comment by fmartingr** [comment]
I'd say the path going forward should be: Download the bookmark archive/article/thumb/ebook to a temporary folder. If everything goes ok, we replace the old ones, if not, we raise an error. But it should be open enough to allow multiple operations.

This is a bigger task that you may think, and we need to refactor the logic into smaller chunks to made them easily testable.

File: internal/core/ebook.go [hunk 1]
```diff
@@ -40,34 +40,22 @@ func GenerateEbook(req ProcessRequest) (book model.Bookmark, err error) {
...
-	if _, err := os.Stat(ebookDir); os.IsNotExist(err) {
-		err := os.MkdirAll(ebookDir, model.DataDirPerm)
-		if err != nil {
-			return book, errors.Wrap(err, "can't create ebook directory")
-		}
-	}
-	// create epub file
-	epubFile, err := os.Create(ebookfile)
+	// create temporary epub file
+	tmpFile, err := os.CreateTemp("", "ebook*.epub")
```
Comment (fmartingr) [inline internal/core/ebook.go:50]: Why an asterisk in the file name?

File: internal/core/processing.go [hunk 2]
```diff
@@ -236,12 +243,43 @@ func downloadBookImage(url, dstPath string) error {
...
 
+	err = MoveToDestination(dstPath, tmpFile)
+	if err != nil {
+		return err
+	}
+
+	return nil
+}
+
+func MoveToDestination(dstPath string, tmpFile *os.File) error {
```
Comment (fmartingr) [inline internal/core/processing.go:261]: I would use `MoveFileToDestination` in case we want to have something for folders later.
```suggestion
func MoveFileToDestination(dstPath string, tmpFile *os.File) error {
```

Comment (fmartingr) [reply internal/core/processing.go:261]: Add comment making clear that `dstPath` requires the filename. You can add a third argument for the filename, up to you.

File: internal/core/processing.go [hunk 3]
```diff
@@ -101,6 +103,8 @@ func ProcessBookmark(req ProcessRequest) (book model.Bookmark, isFatalErr bool,
 		// Get image URL
 		if article.Image != "" {
 			imageURLs = append(imageURLs, article.Image)
+		} else {
+			os.Remove(imgPath)
```
Comment (fmartingr) [inline internal/core/processing.go:107]: I would remove this from here and let `downloadBookImage` do the cleanup work.

File: internal/core/processing.go [hunk 4]
```diff
@@ -115,9 +119,6 @@ func ProcessBookmark(req ProcessRequest) (book model.Bookmark, isFatalErr bool,
 	}
 
 	// Save article image to local disk
-	strID := strconv.Itoa(book.ID)
-	imgPath := fp.Join(req.DataDir, "thumb", strID)
-
 	for _, imageURL := range imageURLs {
 		err = downloadBookImage(imageURL, imgPath)
```
Comment (fmartingr) [inline internal/core/processing.go:123]: Log something if `err != nil`

File: internal/view/assets/js/page/home.js [hunk 5]
```diff
@@ -702,15 +702,35 @@ export default {
...
+                            if (data.createEbook && !book.hasEbook){
+                                faildCreateEbook.push(book.id);
+                            }
+                        }),
+
+                        this.showDialog({
+                            title: `Update Archive Error`,
+                            content: `Bookmarks Update Archive Faild : ${faildUpdateArchives.join(", ")} 
+                            Bookmarks  Create Ebook Faild: ${faildCreateEbook.join(",")} 
+                            We recovered the last available version.`,
```
[the remark this answers is not in the document]
Comment (fmartingr) [reply internal/view/assets/js/page/home.js:724]: Have you tried `<br>` ?

File: internal/webserver/handler-ui.go [hunk 6]
```diff
@@ -320,7 +320,7 @@ func (h *Handler) ServeBookmarkEbook(w http.ResponseWriter, r *http.Request, ps
 	}
 
 	// Check if it has ebook.
-	ebookPath := fp.Join(h.DataDir, "ebook", strID+".epub")
+	ebookPath := fp.Join(h.DataDir, "ebook", strID)
```
Comment (fmartingr) [inline internal/webserver/handler-ui.go:323]: Changing this will make it not backwards compatible. People that have ebooks stored and upgrade to this change wont be able to download their ebooks, ebook will be downloaded again and the old one (without extension) will be left in the filesystem.

File: internal/webserver/handler-api.go [hunk 7]
```diff
@@ -110,7 +110,7 @@ func (h *Handler) ApiGetBookmarks(w http.ResponseWriter, r *http.Request, ps htt
 		strID := strconv.Itoa(bookmarks[i].ID)
 		imgPath := fp.Join(h.DataDir, "thumb", strID)
 		archivePath := fp.Join(h.DataDir, "archive", strID)
-		ebookPath := fp.Join(h.DataDir, "ebook", strID+".epub")
+		ebookPath := fp.Join(h.DataDir, "ebook", strID)
```
Comment (fmartingr) [inline internal/webserver/handler-api.go:113]: Read comment in `handler-ui.go`

File: internal/webserver/handler-api.go [hunk 8]
```diff
@@ -285,7 +285,7 @@ func (h *Handler) ApiDeleteBookmark(w http.ResponseWriter, r *http.Request, ps h
 		strID := strconv.Itoa(id)
 		imgPath := fp.Join(h.DataDir, "thumb", strID)
 		archivePath := fp.Join(h.DataDir, "archive", strID)
-		ebookPath := fp.Join(h.DataDir, "ebook", strID+".epub")
+		ebookPath := fp.Join(h.DataDir, "ebook", strID)
```
Comment (fmartingr) [inline internal/webserver/handler-api.go:288]: Read comment in `handler-ui.go`

File: internal/webserver/handler-api.go [hunk 9]
```diff
@@ -434,12 +434,32 @@ func (h *Handler) ApiDownloadEbook(w http.ResponseWriter, r *http.Request, ps ht
 				ContentType: contentType,
 			}
 
-			book, err = core.GenerateEbook(request)
-			content.Close()
+			// if file exist book return avilable file
+			strID := strconv.Itoa(book.ID)
+			ebookPath := fp.Join(request.DataDir, "ebook", strID)
```
Comment (fmartingr) [inline internal/webserver/handler-api.go:439]: Here you are not using the `${strID}.epub` filename. We need to be consistent. Maybe creating a function called `GetEbookFilename(book model.Bookmark) string` that receives the bookmark and returns the ebook filename?

File: internal/view/assets/js/page/home.js [hunk 10]
```diff
@@ -702,15 +702,36 @@ export default {
...
+                                faildCreateEbook.push(book.id);
+                            }
+                        });
+                        if(faildCreateEbook.length > 0 || faildUpdateArchives.length > 0){
+                        this.showDialog({
+                            title: `Update Archive Error`,
+                            content: `Bookmarks Update Archive Faild : ${faildUpdateArchives.join(", ")} 
+                            Bookmarks  Create Ebook Faild: ${faildCreateEbook.join(",")} 
+                            We recovered the last available version.`,
+                            mainText: "OK",
```
Comment (fmartingr) [inline internal/view/assets/js/page/home.js:725]:
```suggestion
                            Bookmarks  Create Ebook Failed: ${faildCreateEbook.join(",")} 
                            Files that failed retrieval were not overwritten.`,
                            mainText: "OK",
```

**Review by fmartingr — CHANGES_REQUESTED** [review]
I have done a first pass really quick. I'm concerned about the backwards compatibility if we change the ebook filename now for people that already have 1.5.5. 

I will need to make a second pass trying it out locally.

File: internal/core/ebook.go [hunk 11]
```diff
@@ -223,6 +211,27 @@ img {
...
+	err = epubWriter.Close()
+	if err != nil {
+		return book, errors.Wrap(err, "failed to close EPUB writer")
+	}
+	err = tmpFile.Close()
+	if err != nil {
+		return book, errors.Wrap(err, "failed to close temporary EPUB file")
+	}
+	// open temporary file again
+	tmpFile, err = os.Open(tmpFile.Name())
```
[the remark this answers is not in the document]
Comment (fmartingr) [reply internal/core/ebook.go:224]: Then why not let `MoveFileToDestination` handle opening/closing the file?

File: internal/core/processing.go (hunk 3 above)
Comment (fmartingr) [reply internal/core/processing.go:108]: Oh, of course. You are right 👍

File: internal/view/assets/js/page/home.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (fmartingr) [reply internal/view/assets/js/page/home.js]: Maybe you need to edit the dialog too. Let's keep it all under one line for now, we can fix the texts later.

File: internal/webserver/handler-ui.go (hunk 6 above)
Comment (fmartingr) [reply internal/webserver/handler-ui.go]: We can do something, but it's pretty inconvenient and hard for distributors to build upon. 

Let's move the "ebook exists" logic to one function and let the function:
1. Check the filename without extension
    - If exists, `os.Rename` the file to `id.epub` 
2. Check the `id.epub` extension.

We can remove the first check after some versions.

File: internal/core/ebook.go (hunk 1 above)
Comment (fmartingr) [reply internal/core/ebook.go]: I was asking about the `*` symbol that was in the filename, I don't mind the extension.

File: internal/core/processing.go [hunk 12]
```diff
@@ -115,26 +119,33 @@ func ProcessBookmark(req ProcessRequest) (book model.Bookmark, isFatalErr bool,
...
 	// Save article image to local disk
-	strID := strconv.Itoa(book.ID)
-	imgPath := fp.Join(req.DataDir, "thumb", strID)
-
-	for _, imageURL := range imageURLs {
-		err = downloadBookImage(imageURL, imgPath)
+	for i, imageURL := range imageURLs {
+		err = DownloadBookImage(imageURL, imgPath)
+		if err != nil {
+			if err.Error() == fmt.Sprintf("%s is not a supported image", imageURL) {
```
Comment (fmartingr) [inline internal/core/processing.go:125]: Instead of this, you can create a custom error and check if its in the chain with `errors.Is`:

```go
var ErrNoSupportedImageType = errors.New("unsupported image type")

// func() error
return ErrUnsupportedImageType

// usage

if err != nil && errors.Is(err, ErrUnsupportedImageType) {
    // ...
}
```

File: internal/core/processing_test.go
Comment (fmartingr) [inline internal/core/processing_test.go:1]: I would prefer if tests well contained to the logic they have, something like:

```
func TestMoveFileToDestination(t *testing.T) {
    t.Run("create dir", func(t *testing.T) {
        t.Run("fails", func(t *testing.T) {
            // test cae
        })
    })
}
```

You can even [create a custom struct to handle multiple inputs/outputs and just iteate over it preparing the test](https://github.com/mattermost/mattermost-plugin-mscalendar/blob/master/server/command/connect_test.go#L18-L86), executing the call and then checking the results.

File: internal/view/assets/js/page/home.js [hunk 13]
```diff
@@ -702,15 +702,36 @@ export default {
...
-
-						json.forEach(book => {
-							var item = items.find(el => el.id === book.id);
-							this.bookmarks.splice(item.index, 1, book);
-						});
-					}).catch(err => {
-						this.selection = [];
-						this.editMode = false;
-						this.dialog.loading = false;
+
```
Comment (fmartingr) [inline internal/view/assets/js/page/home.js:705]: I think that to make this simpler for now (since we don't have a nice way of presenting this to the user) I would just expose if everything went right or not.

The error message could look something like `Not all bookmarks could have their contents updated, but no files were overwritten.`

In order to have some debug information, we could expose the IDs in a single `console.error()` statement along with a server log, maybe?

**Review by fmartingr — CHANGES_REQUESTED** [review]
Hey @Monirzadeh, nice work on this. I have pointed out a few things, some minor.

One thing that still worries me is the migration from ebooks without extension to files with extension, you are not still handling that, right? We need to properly take care of that before moving this forward.

**Comment by fmartingr** [comment]
> i decide not to do that in this PR so i revert that in [return .epub](https://github.com/go-shiori/shiori/pull/683/commits/89c04d69390d328fb22b1714dc580b8b027afe59) so it is work like as before.

Oh wait, so you wanted to change from `file.epub` to simply `file` (without extension)?. It thought it was the opposite! 

I think we should leave the extension, so there's nothing to change if that's the case.

File: internal/core/ebook.go [hunk 14]
```diff
@@ -16,6 +16,10 @@ import (
 	"github.com/pkg/errors"
 )
 
+// this function get request and a destination path and will create an epub file in dstPath from that request
+// dstPath should be incouded file name with '.epub'
+// it will return a bookmark model and err
+// bookmark model later use for update UI shiori based on this function be sucssesful or not
```
Comment (fmartingr) [inline internal/core/ebook.go:22]: Made some minor changes, since this should start with the function name.

I'm not sold on this function returning a `model.Bookmark`, but I don't want to change that for now.


```suggestion
// GenerateEbook receives a `ProcessRequest` and generates an ebook file in the destination path specified.
// The destination path `dstPath` should include file name with ".epub" extension
// The bookmark model will be used to update the UI based on whether this function is successful or not.
```

File: internal/core/processing.go [hunk 15]
```diff
@@ -121,15 +123,14 @@ func ProcessBookmark(req ProcessRequest) (book model.Bookmark, isFatalErr bool,
...
-		if err != nil {
-			if err.Error() == fmt.Sprintf("%s is not a supported image", imageURL) {
-				log.Printf("Not found image for URL: %s", imageURL)
-				if i == len(imageURLs)-1 {
-					os.Remove(imgPath)
-				}
-			} else {
-				log.Printf("File download not successful for image URL: %s", imageURL)
+		if err != nil && errors.Is(err, ErrNoSupportedImageType) {
+			log.Printf("Not found image for URL: %s", imageURL)
```
Comment (fmartingr) [inline internal/core/processing.go:127]: Let's print the error with the URL for now, to be consistent.

```suggestion
			log.Printf("%s: %s", err.String(), imageURL)
```

**Review by fmartingr — APPROVED** [review]
Hey, amazing work on this! I have put out two small changes on a docstring and an error handler but this should be good to go as well.

I still think that `MoveFileToDestination` should receive two paths and it should handle opening the file by itself, but we can revisit that later on.

Do you need this merged to start working on the go-epub migration?

**Comment by fmartingr** [comment]
> i should change things in #679 so i review `MoveFileToDestination` there
> i don't like `model.Bookmark` too but current logic for update UI need to return `model.Bookmark`

We can leave it like that for now, don't worry.
